plugins {
    // Versions come from settings.gradle.kts -> pluginManagement.plugins
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.lanfps.client"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.lanfps.client"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0.0"
    }

    /**
     * A checked-in debug keystore is generated by scripts/build-release.sh so the
     * release APK can be signed locally without any interactive step. This is a
     * LAN game distributed by copying the file to a phone - it is deliberately
     * not a Play Store signing setup.
     */
    signingConfigs {
        create("local") {
            val ks = rootProject.file("keystore/lanfps.keystore")
            if (ks.exists()) {
                storeFile = ks
                storePassword = "lanfps"
                keyAlias = "lanfps"
                keyPassword = "lanfps"
            }
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
            isDebuggable = true
        }
        release {
            // R8 is off on purpose: the whole app is ~40 classes, shrinking buys
            // nothing and only adds a way for the build to fail.
            isMinifyEnabled = false
            isShrinkResources = false
            if (rootProject.file("keystore/lanfps.keystore").exists()) {
                signingConfig = signingConfigs.getByName("local")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    buildFeatures {
        buildConfig = false
        viewBinding = false
        compose = false
    }

    packaging {
        resources.excludes += setOf(
            "META-INF/*.kotlin_module",
            "META-INF/AL2.0",
            "META-INF/LGPL2.1",
            "kotlin/**",
            "**/*.txt",
        )
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/kotlin")
            assets.srcDirs("src/main/assets")
        }
    }

    lint {
        abortOnError = false
    }

    testOptions {
        unitTests.all { it.useJUnitPlatform() }
        unitTests.isReturnDefaultValues = true
    }
}

dependencies {
    implementation(project(":shared"))
    // No AndroidX, no Compose, no game engine: the UI is plain framework Views.

    // SnapshotBuffer and Prediction contain no Android API calls, so the
    // interpolation and reconciliation maths can be verified on a plain JVM.
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
}
